version: '3.9'

services:
  db:
    image: postgres:16
    container_name: randomtrust_db
    restart: always
    environment:
      POSTGRES_USER: random_user
      POSTGRES_PASSWORD: random_pass
      POSTGRES_DB: randomtrust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"  # чтобы не требовал авторизацию при входе
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json  # подключаем твой файл
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: ./src/RandomTrust.Web/Dockerfile
    container_name: randomtrust_backend
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=randomtrust;Username=random_user;Password=random_pass"
    ports:
      - "8080:8080"
    depends_on:
      - db


  frontend:
    build:
      context: ./randomtrust_frontend_final_fixed
      dockerfile: Dockerfile
    container_name: randomtrust_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: